// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbJc6jSfjjeIhSPGTOnxOJH7Nuyl7B3DI',
    appId: '1:250385454172:web:1bd21bcd922f484be7c299',
    messagingSenderId: '250385454172',
    projectId: 'streaker-342ad',
    authDomain: 'streaker-342ad.firebaseapp.com',
    storageBucket: 'streaker-342ad.firebasestorage.app',
    measurementId: 'G-Q0P9B8H95T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWY_j-WW27w1fjM70c0vdJbSTftIzonjk',
    appId: '1:250385454172:android:9ed1e4caa6d5f882e7c299',
    messagingSenderId: '250385454172',
    projectId: 'streaker-342ad',
    storageBucket: 'streaker-342ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV_YZHIdqHDUdg8SpdDHXL2--5f_pt_Kw',
    appId: '1:250385454172:ios:92f05b838924f61be7c299',
    messagingSenderId: '250385454172',
    projectId: 'streaker-342ad',
    storageBucket: 'streaker-342ad.firebasestorage.app',
    iosBundleId: 'com.streaker.streaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbJc6jSfjjeIhSPGTOnxOJH7Nuyl7B3DI',
    appId: '1:250385454172:ios:app_id_placeholder',
    messagingSenderId: '250385454172',
    projectId: 'streaker-342ad',
    storageBucket: 'streaker-342ad.firebasestorage.app',
    iosBundleId: 'com.example.streakerFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbJc6jSfjjeIhSPGTOnxOJH7Nuyl7B3DI',
    appId: '1:250385454172:web:1bd21bcd922f484be7c299',
    messagingSenderId: '250385454172',
    projectId: 'streaker-342ad',
    authDomain: 'streaker-342ad.firebaseapp.com',
    storageBucket: 'streaker-342ad.firebasestorage.app',
    measurementId: 'G-Q0P9B8H95T',
  );
}